import { StyleSheet } from "react-native";

import { Colors, Radii, Shadows, Spacing } from "@/constants/theme";

export type StudyStyles = ReturnType<typeof createStudyStyles>;

export const createStudyStyles = (palette: typeof Colors.light) =>
    StyleSheet.create({
        shell: {
            flex: 1,
            flexDirection: "row",
            padding: Spacing.md,
            gap: Spacing.md,
            backgroundColor: palette.background,
        },
        canvasColumn: {
            flex: 4,
            backgroundColor: palette.surface,
            borderRadius: Radii.lg,
            overflow: "hidden",
            borderWidth: 1,
            borderColor: palette.border,
            ...Shadows.sm,
        },
        canvasColumnFullscreen: {
            flex: 1,
        },
        canvasHeader: {
            flexDirection: "row",
            alignItems: "flex-start",
            justifyContent: "space-between",
            gap: Spacing.md,
        },
        canvasTitle: {
            flex: 1,
        },
        tutorToggleButton: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            paddingVertical: 8,
            paddingHorizontal: 12,
            borderRadius: Radii.md,
            backgroundColor: palette.surfaceAlt,
            borderWidth: 1,
            borderColor: palette.border,
        },
        tutorToggleButtonCollapsed: {
            backgroundColor: `${palette.success}12`,
            borderColor: `${palette.success}33`,
        },
        tutorToggleText: {
            color: palette.success,
            fontSize: 14,
            fontWeight: "600",
        },
        collapseTutorButton: {
            padding: 8,
            borderRadius: Radii.md,
            backgroundColor: palette.muted,
        },
        chatColumn: {
            flex: 2,
            backgroundColor: palette.surfaceAlt,
            borderRadius: Radii.lg,
            paddingHorizontal: Spacing.sm,
            paddingVertical: 4,
            gap: 2,
            borderWidth: 1,
            borderColor: palette.border,
            ...Shadows.sm,
        },
        chatColumnCollapsed: {
            width: 60,
            backgroundColor: palette.surfaceAlt,
            borderRadius: Radii.lg,
            paddingVertical: Spacing.md,
            paddingHorizontal: Spacing.sm,
            gap: Spacing.md,
            borderWidth: 1,
            borderColor: palette.border,
            alignItems: "center",
            ...Shadows.sm,
        },
        expandTutorButton: {
            width: 44,
            height: 44,
            borderRadius: Radii.md,
            backgroundColor: `${palette.success}12`,
            borderWidth: 1,
            borderColor: `${palette.success}33`,
            alignItems: "center",
            justifyContent: "center",
            position: "relative",
        },
        messageBadge: {
            position: "absolute",
            top: -6,
            right: -6,
            minWidth: 20,
            height: 20,
            borderRadius: 10,
            backgroundColor: palette.primary,
            alignItems: "center",
            justifyContent: "center",
            paddingHorizontal: 4,
        },
        messageBadgeText: {
            color: palette.textOnPrimary,
            fontSize: 11,
            fontWeight: "700",
        },
        collapsedQuickActions: {
            gap: Spacing.xs,
            alignItems: "center",
        },
        collapsedActionButton: {
            width: 40,
            height: 40,
            borderRadius: Radii.md,
            backgroundColor: palette.muted,
            borderWidth: 1,
            borderColor: palette.border,
            alignItems: "center",
            justifyContent: "center",
        },
        collapsedVoiceInput: {
            marginTop: "auto",
            alignItems: "center",
        },
        collapsedThinking: {
            padding: Spacing.xs,
        },
        canvasArea: {
            padding: Spacing.md,
            gap: Spacing.sm,
        },
        pageNavContainer: {
            marginBottom: Spacing.sm,
        },
        pageTabsContent: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            paddingVertical: 4,
        },
        pageTab: {
            paddingVertical: 8,
            paddingHorizontal: 16,
            borderRadius: Radii.md,
            backgroundColor: palette.surface,
            borderWidth: 1,
            borderColor: palette.border,
            minWidth: 70,
            alignItems: "center",
            justifyContent: "center",
        },
        pageTabActive: {
            backgroundColor: `${palette.primary}12`,
            borderColor: palette.primary,
        },
        pageTabText: {
            fontSize: 13,
            color: palette.textMuted,
            fontWeight: "500",
        },
        pageTabTextActive: {
            color: palette.primary,
            fontWeight: "600",
        },
        pageTitlePreview: {
            overflow: "hidden",
            borderRadius: 4,
        },
        addPageButton: {
            padding: 10,
            borderRadius: Radii.md,
            backgroundColor: `${palette.success}12`,
            borderWidth: 1,
            borderColor: `${palette.success}33`,
            alignItems: "center",
            justifyContent: "center",
        },
        pageTitleContainer: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.sm,
            marginBottom: Spacing.sm,
        },
        pageTitleLabel: {
            fontSize: 13,
            color: palette.textMuted,
            fontWeight: "500",
        },
        pageTitleCanvasWrapper: {
            borderRadius: Radii.md,
            borderWidth: 1,
            borderColor: palette.border,
            backgroundColor: "#f8fafc",
            overflow: "hidden",
        },
        canvasScrollShell: {
            marginTop: 8,
        },
        canvasInnerVertical: {
            paddingBottom: Spacing.sm,
        },
        canvasWrapper: {
            position: "relative",
            // width and height are set dynamically via inline style
        },
        chatHeader: {
            gap: 2,
            marginBottom: -2,
        },
        chatTitleRow: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
        },
        voiceControlsRow: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,

        },
        chatToolbarScroll: {
            marginHorizontal: -4,
            flexShrink: 0,
            marginBottom: -180,
        },
        chatToolbarContent: {
            flexDirection: "row",
            alignItems: "center",
            gap: 2,
            paddingHorizontal: 4,
            paddingVertical: 0,
        },
        ttsToggle: {
            padding: 8,
            borderRadius: Radii.md,
            backgroundColor: palette.muted,
            borderWidth: 1,
            borderColor: palette.border,
            minWidth: 36,
            minHeight: 36,
            alignItems: "center",
            justifyContent: "center",
        },
        ttsToggleActive: {
            backgroundColor: `${palette.success}1a`,
            borderColor: `${palette.success}33`,
        },
        listeningModeActive: {
            backgroundColor: `${palette.warning}1a`,
            borderColor: `${palette.warning}33`,
        },
        toolbarDivider: {
            width: 1,
            height: 32,
            backgroundColor: palette.border,
            opacity: 0.6,
            marginHorizontal: 4,
        },
        quickActionChip: {
            flexDirection: "row",
            alignItems: "center",
            gap: 4,
            backgroundColor: `${palette.primary}12`,
            paddingVertical: 8,
            paddingHorizontal: 12,
            borderRadius: Radii.pill,
            borderWidth: 1,
            borderColor: `${palette.primary}33`,
        },
        quickActionText: {
            color: palette.primary,
            fontSize: 12,
            fontWeight: "500",
        },
        explainButton: {
            flexDirection: "row",
            alignItems: "center",
            gap: 4,
            backgroundColor: `${palette.warning}12`,
            paddingVertical: 8,
            paddingHorizontal: 12,
            borderRadius: Radii.md,
            borderWidth: 1,
            borderColor: `${palette.warning}66`,
            minHeight: 36,
        },
        explainButtonText: {
            color: palette.warning,
            fontWeight: "600",
            fontSize: 13,
        },
        primaryButton: {
            backgroundColor: palette.primary,
            paddingVertical: 8,
            paddingHorizontal: 12,
            borderRadius: Radii.md,
            flexDirection: "row",
            alignItems: "center",
            gap: 4,
            minHeight: 36,
        },
        primaryButtonText: {
            color: palette.textOnPrimary,
            fontWeight: "600",
            fontSize: 13,
        },
        secondaryButton: {
            borderRadius: Radii.md,
            paddingVertical: 8,
            paddingHorizontal: 12,
            borderWidth: 1,
            borderColor: palette.border,
            backgroundColor: palette.surface,
            minHeight: 36,
        },
        secondaryButtonText: {
            color: palette.text,
            fontSize: 13,
        },
        chatList: {
            flex: 1,
            marginHorizontal: -4,
            marginBottom: -2,
        },
        chatBubble: {
            padding: 10,
            paddingHorizontal: 12,
            borderRadius: Radii.md,
            gap: 4,
            borderWidth: 1,
            borderColor: palette.border,
            backgroundColor: palette.surface,
            marginHorizontal: 4,
        },
        bubbleHeader: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
        },
        replayButton: {
            padding: 8,
            minWidth: 44,
            minHeight: 44,
            alignItems: "center",
            justifyContent: "center",
        },
        chatAI: {
            backgroundColor: palette.surfaceAlt,
            borderLeftWidth: 3,
            borderLeftColor: palette.success,
        },
        chatUser: {
            backgroundColor: palette.surface,
            borderLeftWidth: 3,
            borderLeftColor: palette.primary,
        },
        metaText: {
            fontSize: 11,
            color: palette.textMuted,
            marginTop: 4,
        },
        input: {
            borderWidth: 1,
            borderColor: palette.border,
            borderRadius: Radii.md,
            padding: 12,
            minHeight: 120,
            backgroundColor: palette.surface,
            marginTop: Spacing.sm,
            fontSize: 15,
        },
        inputArea: {
            gap: 2,
        },
        voiceRow: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
        },
        thinkingIndicator: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
        },
        submitArea: {
            gap: 4,
        },
        submitButton: {
            backgroundColor: palette.primary,
            paddingVertical: 12,
            paddingHorizontal: 16,
            borderRadius: Radii.md,
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
            gap: Spacing.xs,
        },
        disabledButton: {
            opacity: 0.6,
        },
        center: {
            flex: 1,
            alignItems: "center",
            justifyContent: "center",
            gap: Spacing.sm,
            padding: Spacing.md,
            backgroundColor: palette.background,
        },
        topicFocusBadge: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            backgroundColor: `${palette.success}12`,
            paddingVertical: 6,
            paddingHorizontal: 12,
            borderRadius: Radii.pill,
            alignSelf: "flex-start",
            marginTop: 4,
            borderWidth: 1,
            borderColor: `${palette.success}33`,
        },
        topicFocusText: {
            color: palette.success,
            fontSize: 13,
            fontWeight: "500",
        },
        checkAnswerButton: {
            position: "absolute",
            backgroundColor: palette.primary,
            paddingVertical: 12,
            paddingHorizontal: 16,
            borderRadius: 25,
            flexDirection: "row",
            alignItems: "center",
            gap: 6,
            ...Shadows.md,
            zIndex: 100,
        },
        checkAnswerButtonText: {
            color: palette.textOnPrimary,
            fontWeight: "700",
            fontSize: 16,
        },
        canvasHighlight: {
            position: "absolute",
            borderRadius: Radii.md,
            borderWidth: 3,
            borderColor: "transparent",
            zIndex: 10,
        },
        canvasHighlightFull: {
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
        },
        canvasHighlightActive: {
            borderColor: palette.primary,
            backgroundColor: `${palette.primary}14`,
        },
        answerMarkersContainer: {
            marginTop: Spacing.md,
            padding: Spacing.md,
            backgroundColor: palette.surface,
            borderRadius: Radii.md,
            borderWidth: 1,
            borderColor: palette.border,
        },
        markersTitle: {
            fontSize: 13,
            color: palette.textMuted,
            marginBottom: Spacing.xs,
        },
        markersList: {
            flexDirection: "row",
            flexWrap: "wrap",
            gap: Spacing.xs,
        },
        markerBadge: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            backgroundColor: palette.surface,
            paddingVertical: 8,
            paddingHorizontal: 12,
            borderRadius: Radii.pill,
            borderWidth: 1,
            borderColor: palette.border,
        },
        markerBadgeHighlighted: {
            borderColor: palette.primary,
            backgroundColor: `${palette.primary}12`,
        },
        markerBadgeText: {
            color: palette.success,
            fontWeight: "600",
            fontSize: 13,
        },
        bubbleTitleRow: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
        },
        questionBadge: {
            backgroundColor: `${palette.primary}18`,
            paddingVertical: 2,
            paddingHorizontal: 8,
            borderRadius: 10,
        },
        questionBadgeText: {
            color: palette.primary,
            fontSize: 11,
            fontWeight: "600",
        },
        viewNotesButton: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            marginTop: 8,
            alignSelf: "flex-start",
            backgroundColor: `${palette.primary}10`,
            paddingVertical: 6,
            paddingHorizontal: 10,
            borderRadius: Radii.md,
        },
        viewNotesText: {
            color: palette.primary,
            fontSize: 12,
            fontWeight: "600",
        },
        viewDiagramButton: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            marginTop: 8,
            alignSelf: "flex-start",
            backgroundColor: `${palette.success}12`,
            paddingVertical: 6,
            paddingHorizontal: 10,
            borderRadius: Radii.md,
            borderWidth: 1,
            borderColor: `${palette.success}33`,
        },
        viewDiagramText: {
            color: palette.success,
            fontSize: 12,
            fontWeight: "600",
        },
        citationRow: {
            flexDirection: "row",
            flexWrap: "wrap",
            gap: Spacing.xs,
            marginTop: 6,
        },
        citationChip: {
            flexDirection: "row",
            alignItems: "center",
            gap: 6,
            backgroundColor: `${palette.primary}10`,
            paddingVertical: 6,
            paddingHorizontal: 10,
            borderRadius: Radii.md,
            borderWidth: 1,
            borderColor: `${palette.primary}33`,
        },
        citationChipText: {
            color: palette.primary,
            fontSize: 12,
            fontWeight: "600",
        },
        flashcardNotification: {
            position: "absolute",
            bottom: Spacing.lg,
            left: "50%",
            transform: [{ translateX: -100 }],
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.sm,
            backgroundColor: palette.success,
            paddingVertical: Spacing.sm,
            paddingHorizontal: Spacing.md,
            borderRadius: Radii.pill,
            ...Shadows.md,
        },
        flashcardNotificationText: {
            color: "#fff",
            fontWeight: "600",
            fontSize: 14,
        },
        lecturePassedNotification: {
            position: "absolute",
            bottom: Spacing.lg + 56,
            left: "50%",
            transform: [{ translateX: -120 }],
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.sm,
            backgroundColor: palette.primary,
            paddingVertical: Spacing.sm,
            paddingHorizontal: Spacing.md,
            borderRadius: Radii.pill,
            ...Shadows.md,
        },
        lecturePassedNotificationText: {
            color: "#fff",
            fontWeight: "600",
            fontSize: 14,
        },
    });
