import { StyleSheet } from "react-native";

import { Colors, Radii, Shadows, Spacing } from "@/constants/theme";

export type StudyStyles = ReturnType<typeof createStudyStyles>;

export const createStudyStyles = (palette: typeof Colors.light) =>
    StyleSheet.create({
        shell: {
            flex: 1,
            flexDirection: "row",
            padding: Spacing.md,
            gap: Spacing.md,
            backgroundColor: palette.background,
        },
        canvasColumn: {
            flex: 4,
            backgroundColor: palette.surface,
            borderRadius: Radii.lg,
            overflow: "hidden",
            borderWidth: 1,
            borderColor: palette.border,
            position: "relative",
            ...Shadows.sm,
        },
        canvasColumnFullscreen: {
            flex: 1,
        },
        canvasHeader: {
            flexDirection: "row",
            alignItems: "flex-start",
            justifyContent: "space-between",
            gap: Spacing.md,
        },
        canvasTitle: {
            flex: 1,
        },
        tutorToggleButton: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            paddingVertical: 8,
            paddingHorizontal: 12,
            borderRadius: Radii.md,
            backgroundColor: palette.surfaceAlt,
            borderWidth: 1,
            borderColor: palette.border,
        },
        tutorToggleButtonCollapsed: {
            backgroundColor: `${palette.success}12`,
            borderColor: `${palette.success}33`,
        },
        tutorToggleText: {
            color: palette.success,
            fontSize: 14,
            fontWeight: "600",
        },
        collapseTutorButton: {
            padding: 8,
            borderRadius: Radii.md,
            backgroundColor: palette.glass,
            borderWidth: 1,
            borderColor: `${palette.border}cc`,
        },
        chatColumn: {
            flex: 2,
            backgroundColor: palette.surface,
            borderRadius: Radii.lg,
            padding: Spacing.sm,
            gap: Spacing.xs,
            borderWidth: 1,
            borderColor: palette.border,
            ...Shadows.sm,
        },
        chatColumnFullscreen: {
            flex: 1,
        },
        chatColumnCollapsed: {
            width: 60,
            backgroundColor: palette.surfaceAlt,
            borderRadius: Radii.lg,
            paddingVertical: Spacing.md,
            paddingHorizontal: Spacing.sm,
            gap: Spacing.md,
            borderWidth: 1,
            borderColor: palette.border,
            alignItems: "center",
            ...Shadows.sm,
        },
        expandTutorButton: {
            width: 44,
            height: 44,
            borderRadius: Radii.md,
            backgroundColor: `${palette.success}12`,
            borderWidth: 1,
            borderColor: `${palette.success}33`,
            alignItems: "center",
            justifyContent: "center",
            position: "relative",
        },
        messageBadge: {
            position: "absolute",
            top: -6,
            right: -6,
            minWidth: 20,
            height: 20,
            borderRadius: 10,
            backgroundColor: palette.primary,
            alignItems: "center",
            justifyContent: "center",
            paddingHorizontal: 4,
        },
        messageBadgeText: {
            color: palette.textOnPrimary,
            fontSize: 11,
            fontWeight: "700",
        },
        collapsedQuickActions: {
            gap: Spacing.xs,
            alignItems: "center",
        },
        collapsedActionButton: {
            width: 40,
            height: 40,
            borderRadius: Radii.md,
            backgroundColor: palette.muted,
            borderWidth: 1,
            borderColor: palette.border,
            alignItems: "center",
            justifyContent: "center",
        },
        collapsedVoiceInput: {
            marginTop: "auto",
            alignItems: "center",
        },
        collapsedThinking: {
            padding: Spacing.xs,
        },
        canvasArea: {
            padding: Spacing.md,
            paddingBottom: 118,
            gap: Spacing.sm,
        },
        workspaceRail: {
            gap: Spacing.xs,
            padding: Spacing.sm,
            borderRadius: Radii.md,
            borderWidth: 1,
            borderColor: `${palette.primary}22`,
            backgroundColor: palette.surfaceAlt,
        },
        workspaceRailHeader: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            gap: Spacing.sm,
        },
        workspaceTitleStack: {
            flex: 1,
            gap: 1,
        },
        workspaceTitle: {
            color: palette.text,
            fontSize: 15,
        },
        workspaceSubtitle: {
            color: palette.textMuted,
            fontSize: 12,
            fontWeight: "700",
        },
        referencesButton: {
            flexDirection: "row",
            alignItems: "center",
            gap: 5,
            borderRadius: Radii.pill,
            borderWidth: 1,
            borderColor: `${palette.primary}35`,
            backgroundColor: `${palette.primary}12`,
            paddingVertical: 7,
            paddingHorizontal: 10,
        },
        referencesButtonText: {
            color: palette.primary,
            fontSize: 12,
            fontWeight: "800",
        },
        pageNavContainer: {
            marginBottom: 0,
        },
        pageTabsContent: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            paddingVertical: 2,
        },
        pageTab: {
            paddingVertical: 7,
            paddingHorizontal: 13,
            borderRadius: Radii.pill,
            backgroundColor: palette.surface,
            borderWidth: 1,
            borderColor: palette.border,
            minWidth: 70,
            alignItems: "center",
            justifyContent: "center",
        },
        pageTabActive: {
            backgroundColor: `${palette.primary}12`,
            borderColor: palette.primary,
        },
        pageTabText: {
            fontSize: 13,
            color: palette.textMuted,
            fontWeight: "500",
        },
        pageTabTextActive: {
            color: palette.primary,
            fontWeight: "600",
        },
        pageTitlePreview: {
            overflow: "hidden",
            borderRadius: 4,
        },
        addPageButton: {
            width: 36,
            height: 36,
            borderRadius: 18,
            backgroundColor: `${palette.success}12`,
            borderWidth: 1,
            borderColor: `${palette.success}33`,
            alignItems: "center",
            justifyContent: "center",
        },
        pageTitleContainer: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.sm,
        },
        pageTitleLabel: {
            fontSize: 13,
            color: palette.textMuted,
            fontWeight: "500",
        },
        pageTitleCanvasWrapper: {
            borderRadius: Radii.sm,
            borderWidth: 1,
            borderColor: palette.border,
            backgroundColor: "#f8fafc",
            overflow: "hidden",
        },
        canvasScrollShell: {
            marginTop: 2,
            borderRadius: Radii.md,
            overflow: "hidden",
            borderWidth: 1,
            borderColor: `${palette.border}cc`,
            backgroundColor: "#f8fafc",
            position: "relative",
        },
        canvasInnerVertical: {
            paddingBottom: 0,
        },
        canvasWrapper: {
            position: "relative",
            // width and height are set dynamically via inline style
        },
        gradingCanvasOverlay: {
            position: "absolute",
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
            zIndex: 90,
            alignItems: "center",
            justifyContent: "center",
            padding: Spacing.md,
            backgroundColor: "rgba(248, 250, 252, 0.68)",
        },
        gradingCanvasCard: {
            width: "100%",
            maxWidth: 460,
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.sm,
            borderRadius: Radii.lg,
            borderWidth: 1,
            borderColor: `${palette.warning}66`,
            backgroundColor: palette.surface,
            padding: Spacing.md,
            ...Shadows.md,
        },
        gradingCanvasIcon: {
            width: 42,
            height: 42,
            borderRadius: 15,
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: palette.warning,
        },
        gradingCanvasCopy: {
            flex: 1,
            gap: 3,
        },
        gradingCanvasTitle: {
            color: palette.text,
            fontSize: 16,
            fontWeight: "900",
        },
        gradingCanvasSubtitle: {
            color: palette.textMuted,
            fontSize: 13,
            lineHeight: 18,
            fontWeight: "700",
        },
        chatHeader: {
            gap: Spacing.sm,
            backgroundColor: palette.primaryStrong,
            borderRadius: Radii.lg,
            padding: Spacing.md,
            borderWidth: 1,
            borderColor: `${palette.accent}44`,
        },
        chatTitleRow: {
            flexDirection: "row",
            alignItems: "flex-start",
            justifyContent: "space-between",
            gap: Spacing.sm,
        },
        tutorIdentity: {
            flex: 1,
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.sm,
        },
        tutorAvatar: {
            width: 54,
            height: 54,
            borderRadius: 18,
            backgroundColor: palette.success,
            alignItems: "center",
            justifyContent: "center",
            borderWidth: 2,
            borderColor: "rgba(255, 255, 255, 0.65)",
            position: "relative",
        },
        tutorAvatarSpark: {
            position: "absolute",
            top: 7,
            right: 8,
            width: 9,
            height: 9,
            borderRadius: 5,
            backgroundColor: palette.warning,
            borderWidth: 1,
            borderColor: "#ffffff",
        },
        tutorTitleStack: {
            flex: 1,
            gap: 3,
        },
        tutorBadge: {
            flexDirection: "row",
            alignItems: "center",
            gap: 4,
            alignSelf: "flex-start",
            backgroundColor: "rgba(255, 255, 255, 0.12)",
            borderWidth: 1,
            borderColor: "rgba(255, 255, 255, 0.18)",
            borderRadius: Radii.pill,
            paddingVertical: 4,
            paddingHorizontal: 8,
        },
        tutorBadgeText: {
            color: "#f8fafc",
            fontSize: 11,
            fontWeight: "800",
        },
        tutorTitle: {
            color: "#ffffff",
            fontSize: 24,
            lineHeight: 30,
        },
        tutorStatusRow: {
            flexDirection: "row",
            alignItems: "center",
            gap: 6,
        },
        tutorStatusDot: {
            width: 8,
            height: 8,
            borderRadius: 4,
            backgroundColor: palette.success,
        },
        tutorStatusText: {
            color: "#cbd5e1",
            fontSize: 12,
            fontWeight: "700",
        },
        voiceControlsRow: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,

        },
        chatSubtitle: {
            color: palette.text,
            fontSize: 13,
            fontWeight: "600",
            flex: 1,
            lineHeight: 18,
        },
        tutorFocusCard: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            backgroundColor: `${palette.accent}12`,
            borderWidth: 1,
            borderColor: `${palette.accent}2f`,
            borderRadius: Radii.md,
            paddingVertical: 9,
            paddingHorizontal: 10,
        },
        tutorFocusIcon: {
            width: 28,
            height: 28,
            borderRadius: 10,
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: `${palette.accent}1f`,
        },
        recallTimerBanner: {
            backgroundColor: `${palette.warning}12`,
            borderWidth: 1,
            borderColor: `${palette.warning}55`,
            borderRadius: Radii.md,
            padding: Spacing.sm,
            gap: 8,
        },
        recallTimerHeader: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
        },
        recallTimerText: {
            color: palette.warning,
            fontSize: 14,
            fontWeight: "700",
        },
        recallTimerTrack: {
            height: 6,
            borderRadius: 999,
            backgroundColor: `${palette.warning}24`,
            overflow: "hidden",
        },
        recallTimerFill: {
            height: 6,
            borderRadius: 999,
            backgroundColor: palette.warning,
        },
        finalQuizBanner: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            backgroundColor: `${palette.primary}12`,
            borderWidth: 1,
            borderColor: `${palette.primary}33`,
            borderRadius: Radii.md,
            paddingVertical: 8,
            paddingHorizontal: 12,
        },
        finalQuizBannerText: {
            color: palette.primary,
            fontSize: 13,
            fontWeight: "700",
        },
        warmupBanner: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            backgroundColor: `${palette.success}12`,
            borderWidth: 1,
            borderColor: `${palette.success}33`,
            borderRadius: Radii.md,
            paddingVertical: 8,
            paddingHorizontal: 12,
        },
        warmupBannerText: {
            color: palette.success,
            fontSize: 13,
            fontWeight: "700",
        },
        warmupCard: {
            gap: Spacing.sm,
            borderRadius: Radii.lg,
            borderWidth: 1,
            borderColor: `${palette.success}55`,
            backgroundColor: `${palette.success}10`,
            padding: Spacing.sm,
        },
        warmupHeader: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.sm,
        },
        warmupIcon: {
            width: 34,
            height: 34,
            borderRadius: 12,
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: palette.success,
        },
        warmupCopy: {
            flex: 1,
            gap: 2,
        },
        warmupTitle: {
            color: palette.text,
            fontSize: 15,
            fontWeight: "900",
        },
        warmupSubtitle: {
            color: palette.textMuted,
            fontSize: 12,
            lineHeight: 17,
            fontWeight: "700",
        },
        warmupQuestion: {
            color: palette.text,
            fontSize: 15,
            lineHeight: 21,
            fontWeight: "800",
        },
        warmupOptions: {
            gap: Spacing.xs,
        },
        warmupOption: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            borderRadius: Radii.md,
            borderWidth: 1,
            borderColor: `${palette.success}30`,
            backgroundColor: palette.surface,
            paddingVertical: 10,
            paddingHorizontal: 10,
            minHeight: 46,
        },
        warmupOptionSelected: {
            borderColor: palette.success,
            backgroundColor: `${palette.success}14`,
        },
        warmupOptionCorrect: {
            borderColor: palette.success,
            backgroundColor: `${palette.success}1f`,
        },
        warmupOptionWrong: {
            borderColor: palette.danger,
            backgroundColor: `${palette.danger}12`,
        },
        warmupOptionMarker: {
            width: 26,
            height: 26,
            borderRadius: 9,
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: palette.surfaceAlt,
            borderWidth: 1,
            borderColor: palette.border,
        },
        warmupOptionMarkerText: {
            color: palette.text,
            fontSize: 12,
            fontWeight: "900",
        },
        warmupOptionText: {
            flex: 1,
            color: palette.text,
            fontSize: 13,
            lineHeight: 18,
            fontWeight: "700",
        },
        warmupFeedback: {
            gap: 3,
            borderRadius: Radii.md,
            borderWidth: 1,
            borderColor: `${palette.success}33`,
            backgroundColor: palette.surface,
            padding: Spacing.sm,
        },
        warmupFeedbackTitle: {
            color: palette.text,
            fontSize: 13,
            fontWeight: "900",
        },
        warmupFeedbackText: {
            color: palette.textMuted,
            fontSize: 12,
            lineHeight: 17,
            fontWeight: "700",
        },
        gradingStatusCard: {
            gap: Spacing.sm,
            backgroundColor: `${palette.warning}12`,
            borderWidth: 1,
            borderColor: `${palette.warning}66`,
            borderRadius: Radii.lg,
            padding: Spacing.sm,
        },
        gradingStatusHeader: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.sm,
        },
        gradingStatusIcon: {
            width: 36,
            height: 36,
            borderRadius: 13,
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: palette.warning,
        },
        gradingStatusCopy: {
            flex: 1,
            gap: 2,
        },
        gradingStatusTitle: {
            color: palette.text,
            fontSize: 14,
            fontWeight: "900",
        },
        gradingStatusSubtitle: {
            color: palette.textMuted,
            fontSize: 12,
            lineHeight: 17,
            fontWeight: "700",
        },
        gradingStatusSteps: {
            flexDirection: "row",
            flexWrap: "wrap",
            gap: Spacing.xs,
        },
        gradingStatusStep: {
            flexDirection: "row",
            alignItems: "center",
            gap: 6,
            borderRadius: Radii.pill,
            borderWidth: 1,
            borderColor: `${palette.warning}44`,
            backgroundColor: palette.surface,
            paddingVertical: 6,
            paddingHorizontal: 9,
        },
        gradingStatusStepIcon: {
            width: 22,
            height: 22,
            borderRadius: 8,
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: `${palette.warning}28`,
        },
        gradingStatusStepText: {
            color: palette.text,
            fontSize: 12,
            fontWeight: "800",
        },
        diagnosticAttemptCard: {
            gap: Spacing.sm,
            borderRadius: Radii.lg,
            borderWidth: 1,
            borderColor: `${palette.success}55`,
            backgroundColor: `${palette.success}10`,
            padding: Spacing.sm,
        },
        diagnosticAttemptHeader: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.sm,
        },
        diagnosticAttemptIcon: {
            width: 34,
            height: 34,
            borderRadius: 12,
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: palette.success,
        },
        diagnosticAttemptCopy: {
            flex: 1,
            gap: 2,
        },
        diagnosticAttemptTitle: {
            color: palette.text,
            fontSize: 15,
            fontWeight: "900",
        },
        diagnosticAttemptSubtitle: {
            color: palette.textMuted,
            fontSize: 12,
            lineHeight: 17,
            fontWeight: "700",
        },
        diagnosticAttemptQuestion: {
            color: palette.text,
            fontSize: 14,
            lineHeight: 20,
            fontWeight: "700",
        },
        diagnosticAttemptInput: {
            borderWidth: 1,
            borderColor: `${palette.success}44`,
            borderRadius: Radii.md,
            padding: 12,
            minHeight: 76,
            maxHeight: 130,
            backgroundColor: palette.surface,
            color: palette.text,
            fontSize: 14,
        },
        diagnosticAttemptActions: {
            flexDirection: "row",
            flexWrap: "wrap",
            alignItems: "center",
            gap: Spacing.xs,
        },
        noClueButton: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
            gap: Spacing.xs,
            borderRadius: Radii.md,
            borderWidth: 1,
            borderColor: `${palette.success}44`,
            backgroundColor: palette.surface,
            paddingVertical: 11,
            paddingHorizontal: 14,
        },
        noClueButtonText: {
            color: palette.success,
            fontSize: 13,
            fontWeight: "800",
        },
        chatToolbarScroll: {
            marginHorizontal: -4,
            flexShrink: 0,
            flexGrow: 0,
            height: 52,
            maxHeight: 52,
        },
        chatToolbarContent: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            paddingHorizontal: 4,
            paddingVertical: 4,
        },
        ttsToggle: {
            padding: 8,
            borderRadius: Radii.md,
            backgroundColor: palette.muted,
            borderWidth: 1,
            borderColor: palette.border,
            minWidth: 36,
            minHeight: 36,
            alignItems: "center",
            justifyContent: "center",
        },
        ttsToggleActive: {
            backgroundColor: `${palette.success}1a`,
            borderColor: `${palette.success}33`,
        },
        listeningModeActive: {
            backgroundColor: `${palette.warning}1a`,
            borderColor: `${palette.warning}33`,
        },
        toolbarDivider: {
            width: 1,
            height: 32,
            backgroundColor: palette.border,
            opacity: 0.6,
            marginHorizontal: 4,
        },
        quickActionChip: {
            flexDirection: "row",
            alignItems: "center",
            gap: 4,
            backgroundColor: `${palette.primary}12`,
            paddingVertical: 8,
            paddingHorizontal: 12,
            borderRadius: Radii.pill,
            borderWidth: 1,
            borderColor: `${palette.primary}33`,
        },
        quickActionText: {
            color: palette.primary,
            fontSize: 12,
            fontWeight: "500",
        },
        explainButton: {
            flexDirection: "row",
            alignItems: "center",
            gap: 4,
            backgroundColor: `${palette.warning}12`,
            paddingVertical: 8,
            paddingHorizontal: 12,
            borderRadius: Radii.md,
            borderWidth: 1,
            borderColor: `${palette.warning}66`,
            minHeight: 36,
        },
        explainButtonText: {
            color: palette.warning,
            fontWeight: "600",
            fontSize: 13,
        },
        primaryButton: {
            backgroundColor: palette.primary,
            paddingVertical: 8,
            paddingHorizontal: 12,
            borderRadius: Radii.md,
            flexDirection: "row",
            alignItems: "center",
            gap: 4,
            minHeight: 36,
        },
        primaryButtonText: {
            color: palette.textOnPrimary,
            fontWeight: "600",
            fontSize: 13,
        },
        secondaryButton: {
            borderRadius: Radii.md,
            paddingVertical: 8,
            paddingHorizontal: 12,
            borderWidth: 1,
            borderColor: palette.border,
            backgroundColor: palette.surface,
            minHeight: 36,
        },
        secondaryButtonText: {
            color: palette.text,
            fontSize: 13,
        },
        chatList: {
            flex: 1,
            marginHorizontal: -4,
        },
        chatBubble: {
            padding: 12,
            paddingHorizontal: 13,
            borderRadius: Radii.lg,
            gap: 8,
            borderWidth: 1,
            borderColor: palette.border,
            backgroundColor: palette.surface,
            marginHorizontal: 4,
        },
        bubbleHeader: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            gap: Spacing.xs,
        },
        replayButton: {
            padding: 8,
            minWidth: 44,
            minHeight: 44,
            alignItems: "center",
            justifyContent: "center",
        },
        chatAI: {
            backgroundColor: palette.surfaceAlt,
            borderColor: `${palette.success}33`,
            borderLeftWidth: 4,
            borderLeftColor: palette.success,
        },
        chatUser: {
            backgroundColor: palette.primaryStrong,
            borderColor: `${palette.primary}55`,
            borderLeftWidth: 4,
            borderLeftColor: palette.primary,
        },
        metaText: {
            fontSize: 11,
            color: palette.textMuted,
            marginTop: 4,
        },
        input: {
            borderWidth: 1,
            borderColor: palette.border,
            borderRadius: Radii.md,
            padding: 12,
            minHeight: 120,
            backgroundColor: palette.surface,
            marginTop: Spacing.sm,
            fontSize: 15,
        },
        inputArea: {
            gap: 8,
            flexShrink: 0,
        },
        chatTextInputRow: {
            flexDirection: "row",
            alignItems: "flex-end",
            gap: Spacing.xs,
        },
        chatTextInput: {
            flex: 1,
            borderWidth: 1,
            borderColor: palette.border,
            borderRadius: Radii.md,
            paddingHorizontal: 12,
            paddingVertical: 10,
            minHeight: 44,
            maxHeight: 110,
            backgroundColor: palette.surface,
            color: palette.text,
            fontSize: 14,
        },
        chatSendButton: {
            width: 44,
            height: 44,
            borderRadius: Radii.md,
            backgroundColor: palette.primary,
            alignItems: "center",
            justifyContent: "center",
        },
        answerTextInput: {
            borderWidth: 1,
            borderColor: palette.border,
            borderRadius: Radii.md,
            padding: 12,
            minHeight: 72,
            backgroundColor: palette.surface,
            color: palette.text,
            fontSize: 14,
        },
        voiceRow: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
        },
        thinkingIndicator: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            backgroundColor: `${palette.success}12`,
            borderWidth: 1,
            borderColor: `${palette.success}33`,
            borderRadius: Radii.pill,
            paddingVertical: 6,
            paddingHorizontal: 10,
        },
        submitArea: {
            gap: 4,
        },
        submitButton: {
            backgroundColor: palette.primary,
            paddingVertical: 12,
            paddingHorizontal: 16,
            borderRadius: Radii.md,
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "center",
            gap: Spacing.xs,
        },
        disabledButton: {
            opacity: 0.6,
        },
        center: {
            flex: 1,
            alignItems: "center",
            justifyContent: "center",
            gap: Spacing.sm,
            padding: Spacing.md,
            backgroundColor: palette.background,
        },
        topicFocusBadge: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            backgroundColor: `${palette.success}12`,
            paddingVertical: 6,
            paddingHorizontal: 12,
            borderRadius: Radii.pill,
            alignSelf: "flex-start",
            marginTop: 4,
            borderWidth: 1,
            borderColor: `${palette.success}33`,
        },
        answerModeBanner: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            backgroundColor: `${palette.primary}12`,
            borderWidth: 1,
            borderColor: `${palette.primary}33`,
            borderRadius: Radii.md,
            paddingVertical: 10,
            paddingHorizontal: 12,
            flexWrap: "wrap",
        },
        answerModeBannerIcon: {
            width: 28,
            height: 28,
            borderRadius: 10,
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: palette.primary,
        },
        answerModeBannerText: {
            color: palette.primary,
            fontSize: 14,
            fontWeight: "700",
            flex: 1,
        },
        referenceSummaryButton: {
            flexDirection: "row",
            alignItems: "center",
            gap: 5,
            borderRadius: Radii.pill,
            borderWidth: 1,
            borderColor: `${palette.primary}33`,
            backgroundColor: palette.surface,
            paddingVertical: 7,
            paddingHorizontal: 10,
        },
        referenceSummaryText: {
            color: palette.primary,
            fontSize: 12,
            fontWeight: "800",
        },
        topicFocusText: {
            color: palette.success,
            fontSize: 13,
            fontWeight: "500",
        },
        depthProgressContainer: {
            backgroundColor: palette.surface,
            borderWidth: 1,
            borderColor: `${palette.primary}26`,
            borderRadius: Radii.md,
            padding: Spacing.sm,
            gap: Spacing.xs,
        },
        depthProgressHeader: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            gap: Spacing.sm,
            flexWrap: "wrap",
        },
        depthProgressTitleRow: {
            flex: 1,
            minWidth: 220,
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
        },
        depthProgressIcon: {
            width: 30,
            height: 30,
            borderRadius: 11,
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: `${palette.primary}14`,
            borderWidth: 1,
            borderColor: `${palette.primary}24`,
        },
        depthProgressTitleStack: {
            flex: 1,
            gap: 1,
        },
        depthProgressTitle: {
            color: palette.text,
            fontSize: 13,
            fontWeight: "900",
        },
        depthProgressSubtitle: {
            color: palette.textMuted,
            fontSize: 11,
            lineHeight: 15,
            fontWeight: "700",
        },
        depthProgressSummary: {
            borderRadius: Radii.pill,
            backgroundColor: `${palette.accent}14`,
            borderWidth: 1,
            borderColor: `${palette.accent}30`,
            paddingVertical: 5,
            paddingHorizontal: 9,
        },
        depthProgressSummaryText: {
            color: palette.accent,
            fontSize: 11,
            fontWeight: "900",
        },
        depthOverallTrack: {
            height: 6,
            borderRadius: Radii.pill,
            overflow: "hidden",
            backgroundColor: `${palette.primary}16`,
        },
        depthOverallFill: {
            height: 6,
            borderRadius: Radii.pill,
            backgroundColor: palette.success,
        },
        depthStageScrollContent: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            paddingVertical: 2,
        },
        depthStageButton: {
            width: 126,
            minHeight: 84,
            borderRadius: Radii.md,
            borderWidth: 1,
            borderColor: `${palette.border}dd`,
            backgroundColor: palette.surfaceAlt,
            padding: 9,
            gap: 5,
        },
        depthStageButtonPassed: {
            borderColor: `${palette.success}55`,
            backgroundColor: `${palette.success}12`,
        },
        depthStageButtonCurrent: {
            borderColor: `${palette.warning}66`,
            backgroundColor: `${palette.warning}12`,
        },
        depthStageMetaRow: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            gap: Spacing.xs,
        },
        depthStageNumber: {
            color: palette.textMuted,
            fontSize: 10,
            fontWeight: "900",
            textTransform: "uppercase",
        },
        depthStageLabel: {
            color: palette.text,
            fontSize: 13,
            fontWeight: "900",
            lineHeight: 17,
        },
        depthStageLabelPassed: {
            color: palette.success,
        },
        depthStageLabelCurrent: {
            color: palette.warning,
        },
        depthStageTrack: {
            height: 5,
            borderRadius: Radii.pill,
            overflow: "hidden",
            backgroundColor: `${palette.textMuted}1f`,
        },
        depthStageFill: {
            height: 5,
            borderRadius: Radii.pill,
            backgroundColor: palette.textMuted,
        },
        depthStageFillPassed: {
            backgroundColor: palette.success,
        },
        depthStageFillCurrent: {
            backgroundColor: palette.warning,
        },
        depthStageStatus: {
            color: palette.textMuted,
            fontSize: 11,
            fontWeight: "800",
        },
        depthStageStatusPassed: {
            color: palette.success,
        },
        depthStageStatusCurrent: {
            color: palette.warning,
        },
        depthStageModalBackdrop: {
            flex: 1,
            alignItems: "center",
            justifyContent: "center",
            padding: Spacing.md,
            backgroundColor: "rgba(15, 23, 42, 0.58)",
        },
        depthStageModal: {
            width: "100%",
            maxWidth: 480,
            borderRadius: Radii.lg,
            borderWidth: 1,
            borderColor: `${palette.primary}30`,
            backgroundColor: palette.surface,
            padding: Spacing.md,
            gap: Spacing.md,
            ...Shadows.md,
        },
        depthStageModalHeader: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.sm,
        },
        depthStageModalIcon: {
            width: 42,
            height: 42,
            borderRadius: 14,
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: palette.primary,
        },
        depthStageModalTitleStack: {
            flex: 1,
            gap: 2,
        },
        depthStageModalEyebrow: {
            color: palette.textMuted,
            fontSize: 11,
            fontWeight: "900",
            textTransform: "uppercase",
        },
        depthStageModalTitle: {
            color: palette.text,
            fontSize: 20,
            lineHeight: 25,
            fontWeight: "900",
        },
        depthStageModalClose: {
            width: 36,
            height: 36,
            borderRadius: 12,
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: palette.surfaceAlt,
            borderWidth: 1,
            borderColor: palette.border,
        },
        depthStageDetailBlock: {
            gap: 5,
        },
        depthStageDetailLabel: {
            color: palette.primary,
            fontSize: 12,
            fontWeight: "900",
            textTransform: "uppercase",
        },
        depthStageDetailText: {
            color: palette.text,
            fontSize: 14,
            lineHeight: 20,
            fontWeight: "600",
        },
        depthStageSignalBox: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            borderRadius: Radii.md,
            borderWidth: 1,
            borderColor: `${palette.primary}26`,
            backgroundColor: `${palette.primary}10`,
            padding: Spacing.sm,
        },
        depthStageSignalText: {
            flex: 1,
            color: palette.text,
            fontSize: 13,
            lineHeight: 18,
            fontWeight: "800",
        },
        checkAnswerButton: {
            position: "absolute",
            backgroundColor: palette.primary,
            paddingVertical: 12,
            paddingHorizontal: 16,
            borderRadius: 25,
            flexDirection: "row",
            alignItems: "center",
            gap: 6,
            ...Shadows.md,
            zIndex: 100,
        },
        checkAnswerButtonText: {
            color: palette.textOnPrimary,
            fontWeight: "700",
            fontSize: 16,
        },
        canvasHighlight: {
            position: "absolute",
            borderRadius: Radii.md,
            borderWidth: 3,
            borderColor: "transparent",
            zIndex: 10,
        },
        canvasHighlightFull: {
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
        },
        canvasHighlightActive: {
            borderColor: palette.primary,
            backgroundColor: `${palette.primary}14`,
        },
        answerMarkersContainer: {
            marginTop: Spacing.md,
            padding: Spacing.md,
            backgroundColor: palette.surface,
            borderRadius: Radii.md,
            borderWidth: 1,
            borderColor: palette.border,
        },
        markersTitle: {
            fontSize: 13,
            color: palette.textMuted,
            marginBottom: Spacing.xs,
        },
        markersList: {
            flexDirection: "row",
            flexWrap: "wrap",
            gap: Spacing.xs,
        },
        markerBadge: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            backgroundColor: palette.surface,
            paddingVertical: 8,
            paddingHorizontal: 12,
            borderRadius: Radii.pill,
            borderWidth: 1,
            borderColor: palette.border,
        },
        markerBadgeHighlighted: {
            borderColor: palette.primary,
            backgroundColor: `${palette.primary}12`,
        },
        markerBadgeText: {
            color: palette.success,
            fontWeight: "600",
            fontSize: 13,
        },
        bubbleTitleRow: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            flex: 1,
            flexWrap: "wrap",
        },
        bubbleRoleIcon: {
            width: 26,
            height: 26,
            borderRadius: 10,
            alignItems: "center",
            justifyContent: "center",
            borderWidth: 1,
        },
        bubbleRoleIconTutor: {
            backgroundColor: `${palette.success}12`,
            borderColor: `${palette.success}33`,
        },
        bubbleRoleIconUser: {
            backgroundColor: "rgba(255, 255, 255, 0.12)",
            borderColor: "rgba(255, 255, 255, 0.2)",
        },
        bubbleRoleTextStack: {
            gap: 1,
            minWidth: 74,
        },
        bubbleTutorLabel: {
            color: palette.success,
            fontSize: 13,
        },
        bubbleUserLabel: {
            color: "#dbeafe",
            fontSize: 13,
        },
        bubbleLiveRow: {
            flexDirection: "row",
            alignItems: "center",
            gap: 5,
        },
        bubbleLiveDot: {
            width: 6,
            height: 6,
            borderRadius: 3,
            backgroundColor: palette.warning,
        },
        bubbleLiveText: {
            color: palette.textMuted,
            fontSize: 11,
            fontWeight: "700",
        },
        questionBadge: {
            backgroundColor: `${palette.primary}18`,
            paddingVertical: 2,
            paddingHorizontal: 8,
            borderRadius: 10,
        },
        questionBadgeText: {
            color: palette.primary,
            fontSize: 11,
            fontWeight: "600",
        },
        modelBadge: {
            flexDirection: "row",
            alignItems: "center",
            gap: 4,
            maxWidth: "100%",
            backgroundColor: `${palette.success}14`,
            borderWidth: 1,
            borderColor: `${palette.success}33`,
            borderRadius: Radii.sm,
            paddingVertical: 2,
            paddingHorizontal: 7,
        },
        modelBadgeText: {
            color: palette.text,
            fontSize: 11,
            fontWeight: "600",
            flexShrink: 1,
        },
        reasoningBadge: {
            flexDirection: "row",
            alignItems: "center",
            gap: 4,
            maxWidth: "100%",
            backgroundColor: `${palette.warning}18`,
            borderWidth: 1,
            borderColor: `${palette.warning}55`,
            borderRadius: Radii.sm,
            paddingVertical: 2,
            paddingHorizontal: 7,
        },
        reasoningBadgeText: {
            color: palette.text,
            fontSize: 11,
            fontWeight: "800",
            flexShrink: 1,
        },
        viewNotesButton: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            marginTop: 8,
            alignSelf: "flex-start",
            backgroundColor: `${palette.primary}10`,
            paddingVertical: 6,
            paddingHorizontal: 10,
            borderRadius: Radii.md,
        },
        viewNotesText: {
            color: palette.primary,
            fontSize: 12,
            fontWeight: "600",
        },
        viewDiagramButton: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            marginTop: 8,
            alignSelf: "flex-start",
            backgroundColor: `${palette.success}12`,
            paddingVertical: 6,
            paddingHorizontal: 10,
            borderRadius: Radii.md,
            borderWidth: 1,
            borderColor: `${palette.success}33`,
        },
        viewDiagramText: {
            color: palette.success,
            fontSize: 12,
            fontWeight: "600",
        },
        tutorThinkingCard: {
            gap: Spacing.sm,
            backgroundColor: `${palette.surfaceAlt}f2`,
            borderWidth: 1,
            borderColor: `${palette.warning}55`,
            borderRadius: Radii.md,
            padding: Spacing.sm,
            overflow: "hidden",
            position: "relative",
        },
        tutorThinkingAura: {
            position: "absolute",
            width: 94,
            height: 94,
            borderRadius: 47,
            right: -30,
            top: -42,
            backgroundColor: `${palette.warning}22`,
        },
        tutorThinkingHeader: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.sm,
        },
        tutorThinkingIcon: {
            width: 34,
            height: 34,
            borderRadius: 12,
            backgroundColor: palette.warning,
            alignItems: "center",
            justifyContent: "center",
        },
        tutorThinkingCopy: {
            flex: 1,
            gap: 2,
        },
        tutorThinkingTitle: {
            color: palette.text,
            fontSize: 14,
            fontWeight: "800",
        },
        tutorThinkingSubtitle: {
            color: palette.textMuted,
            fontSize: 12,
            lineHeight: 17,
            fontWeight: "600",
        },
        reasoningTracePanel: {
            flexDirection: "row",
            gap: Spacing.sm,
            borderRadius: Radii.md,
            padding: 10,
            backgroundColor: palette.surface,
            borderWidth: 1,
            borderColor: `${palette.border}cc`,
        },
        reasoningTraceRail: {
            width: 16,
            alignItems: "center",
            paddingVertical: 2,
        },
        reasoningTraceNode: {
            width: 7,
            height: 7,
            borderRadius: 4,
            backgroundColor: palette.accent,
        },
        reasoningTraceNodeStrong: {
            width: 10,
            height: 10,
            borderRadius: 5,
            backgroundColor: palette.warning,
            borderWidth: 2,
            borderColor: palette.surface,
        },
        reasoningTraceLine: {
            width: 2,
            flex: 1,
            minHeight: 18,
            backgroundColor: `${palette.accent}55`,
        },
        reasoningTraceLineAccent: {
            width: 2,
            flex: 1,
            minHeight: 18,
            backgroundColor: `${palette.warning}66`,
        },
        reasoningTraceContent: {
            flex: 1,
            gap: Spacing.xs,
            minWidth: 0,
        },
        reasoningTraceHeaderRow: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            gap: Spacing.xs,
        },
        reasoningTraceTitleRow: {
            flexDirection: "row",
            alignItems: "center",
            gap: 5,
            flexShrink: 1,
            minWidth: 0,
        },
        reasoningTraceTitle: {
            color: palette.text,
            fontSize: 12,
            fontWeight: "900",
            flexShrink: 1,
        },
        reasoningTraceEffort: {
            color: palette.warning,
            fontSize: 11,
            fontWeight: "900",
            flexShrink: 0,
        },
        reasoningMetricGrid: {
            flexDirection: "row",
            flexWrap: "wrap",
            gap: Spacing.xs,
        },
        reasoningMetric: {
            minWidth: 84,
            flexGrow: 1,
            flexBasis: 84,
            borderRadius: Radii.sm,
            paddingVertical: 7,
            paddingHorizontal: 8,
            backgroundColor: `${palette.accent}10`,
            borderWidth: 1,
            borderColor: `${palette.accent}24`,
        },
        reasoningMetricEmphasized: {
            backgroundColor: `${palette.warning}18`,
            borderColor: `${palette.warning}55`,
        },
        reasoningMetricValue: {
            color: palette.text,
            fontSize: 15,
            fontWeight: "900",
        },
        reasoningMetricLabel: {
            color: palette.textMuted,
            fontSize: 10,
            fontWeight: "800",
            marginTop: 1,
        },
        tutorThinkingSteps: {
            gap: Spacing.xs,
        },
        tutorThinkingStep: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            minHeight: 34,
            borderRadius: Radii.md,
            paddingVertical: 7,
            paddingHorizontal: 9,
            backgroundColor: "rgba(255, 255, 255, 0.58)",
            borderWidth: 1,
            borderColor: "rgba(148, 163, 184, 0.22)",
        },
        tutorThinkingStepActive: {
            backgroundColor: `${palette.warning}14`,
            borderColor: `${palette.warning}66`,
        },
        tutorThinkingStepIcon: {
            width: 22,
            height: 22,
            borderRadius: 8,
            backgroundColor: `${palette.warning}22`,
            alignItems: "center",
            justifyContent: "center",
        },
        tutorThinkingStepText: {
            flex: 1,
            color: palette.text,
            fontSize: 12,
            fontWeight: "700",
        },
        tutorThinkingStepPulse: {
            width: 8,
            height: 8,
            borderRadius: 4,
            backgroundColor: palette.success,
        },
        streamingFooter: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            alignSelf: "flex-start",
            backgroundColor: `${palette.success}12`,
            borderWidth: 1,
            borderColor: `${palette.success}33`,
            borderRadius: Radii.pill,
            paddingVertical: 5,
            paddingHorizontal: 9,
        },
        streamingFooterText: {
            color: palette.success,
            fontSize: 11,
            fontWeight: "800",
        },
        citationRow: {
            flexDirection: "row",
            flexWrap: "wrap",
            gap: Spacing.xs,
            marginTop: 6,
        },
        citationChip: {
            flexDirection: "row",
            alignItems: "center",
            gap: 6,
            maxWidth: "100%",
            backgroundColor: `${palette.primary}10`,
            paddingVertical: 6,
            paddingHorizontal: 10,
            borderRadius: Radii.md,
            borderWidth: 1,
            borderColor: `${palette.primary}33`,
        },
        citationSourceBadge: {
            backgroundColor: `${palette.primary}18`,
            borderRadius: Radii.sm,
            paddingVertical: 2,
            paddingHorizontal: 5,
        },
        citationSourceBadgeText: {
            color: palette.primary,
            fontSize: 10,
            fontWeight: "700",
        },
        citationChipText: {
            color: palette.primary,
            flexShrink: 1,
            fontSize: 12,
            fontWeight: "600",
        },
        referenceStrip: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.xs,
            paddingTop: 2,
        },
        referenceChip: {
            flexDirection: "row",
            alignItems: "center",
            gap: 6,
            maxWidth: 240,
            borderRadius: Radii.pill,
            borderWidth: 1,
            borderColor: `${palette.accent}35`,
            backgroundColor: `${palette.accent}10`,
            paddingVertical: 6,
            paddingHorizontal: 10,
        },
        referenceChipSource: {
            color: palette.accent,
            fontSize: 10,
            fontWeight: "900",
        },
        referenceChipText: {
            flexShrink: 1,
            color: palette.text,
            fontSize: 12,
            fontWeight: "700",
        },
        floatingToolDock: {
            position: "absolute",
            left: 14,
            right: 14,
            bottom: 14,
            alignItems: "center",
            zIndex: 120,
        },
        referencesModalBackdrop: {
            flex: 1,
            justifyContent: "flex-end",
            backgroundColor: "rgba(2, 6, 23, 0.52)",
            padding: Spacing.md,
        },
        referencesModal: {
            maxHeight: "72%",
            borderRadius: Radii.lg,
            borderWidth: 1,
            borderColor: `${palette.border}dd`,
            backgroundColor: palette.surface,
            padding: Spacing.md,
            gap: Spacing.sm,
            ...Shadows.md,
        },
        referencesModalHeader: {
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
            gap: Spacing.sm,
        },
        referencesModalTitle: {
            color: palette.text,
            fontSize: 18,
        },
        referencesModalSubtitle: {
            color: palette.textMuted,
            fontSize: 12,
            fontWeight: "700",
        },
        referencesCloseButton: {
            width: 36,
            height: 36,
            borderRadius: 18,
            alignItems: "center",
            justifyContent: "center",
            borderWidth: 1,
            borderColor: palette.border,
            backgroundColor: palette.surfaceAlt,
        },
        referencesModalList: {
            gap: Spacing.xs,
            paddingBottom: Spacing.xs,
        },
        referenceModalRow: {
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.sm,
            borderRadius: Radii.md,
            borderWidth: 1,
            borderColor: palette.border,
            backgroundColor: palette.surfaceAlt,
            padding: Spacing.sm,
        },
        referenceModalIcon: {
            width: 34,
            height: 34,
            borderRadius: 12,
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: `${palette.primary}12`,
        },
        referenceModalTextStack: {
            flex: 1,
            gap: 2,
        },
        referenceModalSource: {
            color: palette.primary,
            fontSize: 11,
            fontWeight: "900",
        },
        referenceModalLabel: {
            color: palette.text,
            fontSize: 13,
            fontWeight: "700",
        },
        referencesEmptyState: {
            minHeight: 120,
            alignItems: "center",
            justifyContent: "center",
            gap: Spacing.xs,
        },
        referencesEmptyText: {
            color: palette.textMuted,
            textAlign: "center",
            fontSize: 13,
            fontWeight: "700",
        },
        flashcardNotification: {
            position: "absolute",
            bottom: Spacing.lg,
            left: "50%",
            transform: [{ translateX: -100 }],
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.sm,
            backgroundColor: palette.success,
            paddingVertical: Spacing.sm,
            paddingHorizontal: Spacing.md,
            borderRadius: Radii.pill,
            ...Shadows.md,
        },
        flashcardNotificationText: {
            color: "#fff",
            fontWeight: "600",
            fontSize: 14,
        },
        lecturePassedNotification: {
            position: "absolute",
            bottom: Spacing.lg + 56,
            left: "50%",
            transform: [{ translateX: -120 }],
            flexDirection: "row",
            alignItems: "center",
            gap: Spacing.sm,
            backgroundColor: palette.primary,
            paddingVertical: Spacing.sm,
            paddingHorizontal: Spacing.md,
            borderRadius: Radii.pill,
            ...Shadows.md,
        },
        lecturePassedNotificationText: {
            color: "#fff",
            fontWeight: "600",
            fontSize: 14,
        },
    });
